# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: KenGeng
description: 'Be an imperfectionist and just do it.'
keywords: "Hexo, NexT"
author: Ken Geng
language: en
timezone: Asia/Shanghai
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://kengeng.github.io/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
skip_render:
  - robots.txt
  - animate/*
  - highlight/*


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''

# Home page setting
index_generator:
  per_page: 4
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next


archive_generator:
  per_page: 12
  yearly: true
  monthly: true
  daily: false

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  lazyload: true

search:
  path: search.xml
  field: post
  content: true
  format: html

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# # Deployment
# ## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

#   type: git
#   repo: git@github.com:KenGeng/KenGeng.github.io.git
#   branch: gh-pages
# Post wordcount display settings
# Dependencies: https://github.com/next-theme/hexo-word-counter
symbols_count_time:
  separated_meta: true
  item_text_total: false